#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiantBeauty
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RadiantDB")]
	public partial class RadiantDataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdministrator(Administrator instance);
    partial void UpdateAdministrator(Administrator instance);
    partial void DeleteAdministrator(Administrator instance);
    partial void InsertAppUser(AppUser instance);
    partial void UpdateAppUser(AppUser instance);
    partial void DeleteAppUser(AppUser instance);
    partial void InsertBeautyProduct(BeautyProduct instance);
    partial void UpdateBeautyProduct(BeautyProduct instance);
    partial void DeleteBeautyProduct(BeautyProduct instance);
    partial void InsertBundleItem(BundleItem instance);
    partial void UpdateBundleItem(BundleItem instance);
    partial void DeleteBundleItem(BundleItem instance);
    partial void InsertBundlePackage(BundlePackage instance);
    partial void UpdateBundlePackage(BundlePackage instance);
    partial void DeleteBundlePackage(BundlePackage instance);
    partial void InsertCustomerOrder(CustomerOrder instance);
    partial void UpdateCustomerOrder(CustomerOrder instance);
    partial void DeleteCustomerOrder(CustomerOrder instance);
    partial void InsertCustomerSkinCondition(CustomerSkinCondition instance);
    partial void UpdateCustomerSkinCondition(CustomerSkinCondition instance);
    partial void DeleteCustomerSkinCondition(CustomerSkinCondition instance);
    partial void InsertOrderItem(OrderItem instance);
    partial void UpdateOrderItem(OrderItem instance);
    partial void DeleteOrderItem(OrderItem instance);
    partial void InsertREVIEW(REVIEW instance);
    partial void UpdateREVIEW(REVIEW instance);
    partial void DeleteREVIEW(REVIEW instance);
    partial void InsertSkinCondition(SkinCondition instance);
    partial void UpdateSkinCondition(SkinCondition instance);
    partial void DeleteSkinCondition(SkinCondition instance);
    partial void InsertUserAddress(UserAddress instance);
    partial void UpdateUserAddress(UserAddress instance);
    partial void DeleteUserAddress(UserAddress instance);
    #endregion
		
		public RadiantDataClassDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RadiantDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RadiantDataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RadiantDataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RadiantDataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RadiantDataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrator> Administrators
		{
			get
			{
				return this.GetTable<Administrator>();
			}
		}
		
		public System.Data.Linq.Table<AppUser> AppUsers
		{
			get
			{
				return this.GetTable<AppUser>();
			}
		}
		
		public System.Data.Linq.Table<BeautyProduct> BeautyProducts
		{
			get
			{
				return this.GetTable<BeautyProduct>();
			}
		}
		
		public System.Data.Linq.Table<BundleItem> BundleItems
		{
			get
			{
				return this.GetTable<BundleItem>();
			}
		}
		
		public System.Data.Linq.Table<BundlePackage> BundlePackages
		{
			get
			{
				return this.GetTable<BundlePackage>();
			}
		}
		
		public System.Data.Linq.Table<CustomerOrder> CustomerOrders
		{
			get
			{
				return this.GetTable<CustomerOrder>();
			}
		}
		
		public System.Data.Linq.Table<CustomerSkinCondition> CustomerSkinConditions
		{
			get
			{
				return this.GetTable<CustomerSkinCondition>();
			}
		}
		
		public System.Data.Linq.Table<OrderItem> OrderItems
		{
			get
			{
				return this.GetTable<OrderItem>();
			}
		}
		
		public System.Data.Linq.Table<REVIEW> REVIEWs
		{
			get
			{
				return this.GetTable<REVIEW>();
			}
		}
		
		public System.Data.Linq.Table<SkinCondition> SkinConditions
		{
			get
			{
				return this.GetTable<SkinCondition>();
			}
		}
		
		public System.Data.Linq.Table<UserAddress> UserAddresses
		{
			get
			{
				return this.GetTable<UserAddress>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrator")]
	public partial class Administrator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdminID;
		
		private string _Role;
		
		private System.DateTime _DateAppointed;
		
		private EntityRef<AppUser> _AppUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnDateAppointedChanging(System.DateTime value);
    partial void OnDateAppointedChanged();
    #endregion
		
		public Administrator()
		{
			this._AppUser = default(EntityRef<AppUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					if (this._AppUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAppointed", DbType="DateTime NOT NULL")]
		public System.DateTime DateAppointed
		{
			get
			{
				return this._DateAppointed;
			}
			set
			{
				if ((this._DateAppointed != value))
				{
					this.OnDateAppointedChanging(value);
					this.SendPropertyChanging();
					this._DateAppointed = value;
					this.SendPropertyChanged("DateAppointed");
					this.OnDateAppointedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_Administrator", Storage="_AppUser", ThisKey="AdminID", OtherKey="UserID", IsForeignKey=true)]
		public AppUser AppUser
		{
			get
			{
				return this._AppUser.Entity;
			}
			set
			{
				AppUser previousValue = this._AppUser.Entity;
				if (((previousValue != value) 
							|| (this._AppUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AppUser.Entity = null;
						previousValue.Administrator = null;
					}
					this._AppUser.Entity = value;
					if ((value != null))
					{
						value.Administrator = this;
						this._AdminID = value.UserID;
					}
					else
					{
						this._AdminID = default(int);
					}
					this.SendPropertyChanged("AppUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppUser")]
	public partial class AppUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _UserSurname;
		
		private string _Email;
		
		private string _PhoneNumber;
		
		private string _HashedPassword;
		
		private string _Gender;
		
		private string _Race;
		
		private System.DateTime _DOB;
		
		private System.Nullable<int> _BillingAddressID;
		
		private System.Nullable<int> _ShippingAddressID;
		
		private System.DateTime _DateCreated;
		
		private System.Nullable<bool> _IsVerified;
		
		private string _VerificationToken;
		
		private System.Nullable<System.DateTime> _VerificationExpiry;
		
		private string _ResetToken;
		
		private System.Nullable<System.DateTime> _ResetTokenExpiry;
		
		private EntityRef<Administrator> _Administrator;
		
		private EntitySet<CustomerOrder> _CustomerOrders;
		
		private EntitySet<CustomerSkinCondition> _CustomerSkinConditions;
		
		private EntitySet<REVIEW> _REVIEWs;
		
		private EntityRef<UserAddress> _UserAddress;
		
		private EntityRef<UserAddress> _UserAddress1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserSurnameChanging(string value);
    partial void OnUserSurnameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnHashedPasswordChanging(string value);
    partial void OnHashedPasswordChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnRaceChanging(string value);
    partial void OnRaceChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnBillingAddressIDChanging(System.Nullable<int> value);
    partial void OnBillingAddressIDChanged();
    partial void OnShippingAddressIDChanging(System.Nullable<int> value);
    partial void OnShippingAddressIDChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnIsVerifiedChanging(System.Nullable<bool> value);
    partial void OnIsVerifiedChanged();
    partial void OnVerificationTokenChanging(string value);
    partial void OnVerificationTokenChanged();
    partial void OnVerificationExpiryChanging(System.Nullable<System.DateTime> value);
    partial void OnVerificationExpiryChanged();
    partial void OnResetTokenChanging(string value);
    partial void OnResetTokenChanged();
    partial void OnResetTokenExpiryChanging(System.Nullable<System.DateTime> value);
    partial void OnResetTokenExpiryChanged();
    #endregion
		
		public AppUser()
		{
			this._Administrator = default(EntityRef<Administrator>);
			this._CustomerOrders = new EntitySet<CustomerOrder>(new Action<CustomerOrder>(this.attach_CustomerOrders), new Action<CustomerOrder>(this.detach_CustomerOrders));
			this._CustomerSkinConditions = new EntitySet<CustomerSkinCondition>(new Action<CustomerSkinCondition>(this.attach_CustomerSkinConditions), new Action<CustomerSkinCondition>(this.detach_CustomerSkinConditions));
			this._REVIEWs = new EntitySet<REVIEW>(new Action<REVIEW>(this.attach_REVIEWs), new Action<REVIEW>(this.detach_REVIEWs));
			this._UserAddress = default(EntityRef<UserAddress>);
			this._UserAddress1 = default(EntityRef<UserAddress>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSurname", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string UserSurname
		{
			get
			{
				return this._UserSurname;
			}
			set
			{
				if ((this._UserSurname != value))
				{
					this.OnUserSurnameChanging(value);
					this.SendPropertyChanging();
					this._UserSurname = value;
					this.SendPropertyChanged("UserSurname");
					this.OnUserSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HashedPassword", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HashedPassword
		{
			get
			{
				return this._HashedPassword;
			}
			set
			{
				if ((this._HashedPassword != value))
				{
					this.OnHashedPasswordChanging(value);
					this.SendPropertyChanging();
					this._HashedPassword = value;
					this.SendPropertyChanged("HashedPassword");
					this.OnHashedPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Race", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Race
		{
			get
			{
				return this._Race;
			}
			set
			{
				if ((this._Race != value))
				{
					this.OnRaceChanging(value);
					this.SendPropertyChanging();
					this._Race = value;
					this.SendPropertyChanged("Race");
					this.OnRaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddressID", DbType="Int")]
		public System.Nullable<int> BillingAddressID
		{
			get
			{
				return this._BillingAddressID;
			}
			set
			{
				if ((this._BillingAddressID != value))
				{
					if (this._UserAddress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBillingAddressIDChanging(value);
					this.SendPropertyChanging();
					this._BillingAddressID = value;
					this.SendPropertyChanged("BillingAddressID");
					this.OnBillingAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddressID", DbType="Int")]
		public System.Nullable<int> ShippingAddressID
		{
			get
			{
				return this._ShippingAddressID;
			}
			set
			{
				if ((this._ShippingAddressID != value))
				{
					if (this._UserAddress1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShippingAddressIDChanging(value);
					this.SendPropertyChanging();
					this._ShippingAddressID = value;
					this.SendPropertyChanged("ShippingAddressID");
					this.OnShippingAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVerified", DbType="Bit")]
		public System.Nullable<bool> IsVerified
		{
			get
			{
				return this._IsVerified;
			}
			set
			{
				if ((this._IsVerified != value))
				{
					this.OnIsVerifiedChanging(value);
					this.SendPropertyChanging();
					this._IsVerified = value;
					this.SendPropertyChanged("IsVerified");
					this.OnIsVerifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerificationToken", DbType="VarChar(64)")]
		public string VerificationToken
		{
			get
			{
				return this._VerificationToken;
			}
			set
			{
				if ((this._VerificationToken != value))
				{
					this.OnVerificationTokenChanging(value);
					this.SendPropertyChanging();
					this._VerificationToken = value;
					this.SendPropertyChanged("VerificationToken");
					this.OnVerificationTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerificationExpiry", DbType="DateTime")]
		public System.Nullable<System.DateTime> VerificationExpiry
		{
			get
			{
				return this._VerificationExpiry;
			}
			set
			{
				if ((this._VerificationExpiry != value))
				{
					this.OnVerificationExpiryChanging(value);
					this.SendPropertyChanging();
					this._VerificationExpiry = value;
					this.SendPropertyChanged("VerificationExpiry");
					this.OnVerificationExpiryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResetToken", DbType="VarChar(64)")]
		public string ResetToken
		{
			get
			{
				return this._ResetToken;
			}
			set
			{
				if ((this._ResetToken != value))
				{
					this.OnResetTokenChanging(value);
					this.SendPropertyChanging();
					this._ResetToken = value;
					this.SendPropertyChanged("ResetToken");
					this.OnResetTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResetTokenExpiry", DbType="DateTime")]
		public System.Nullable<System.DateTime> ResetTokenExpiry
		{
			get
			{
				return this._ResetTokenExpiry;
			}
			set
			{
				if ((this._ResetTokenExpiry != value))
				{
					this.OnResetTokenExpiryChanging(value);
					this.SendPropertyChanging();
					this._ResetTokenExpiry = value;
					this.SendPropertyChanged("ResetTokenExpiry");
					this.OnResetTokenExpiryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_Administrator", Storage="_Administrator", ThisKey="UserID", OtherKey="AdminID", IsUnique=true, IsForeignKey=false)]
		public Administrator Administrator
		{
			get
			{
				return this._Administrator.Entity;
			}
			set
			{
				Administrator previousValue = this._Administrator.Entity;
				if (((previousValue != value) 
							|| (this._Administrator.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Administrator.Entity = null;
						previousValue.AppUser = null;
					}
					this._Administrator.Entity = value;
					if ((value != null))
					{
						value.AppUser = this;
					}
					this.SendPropertyChanged("Administrator");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_CustomerOrder", Storage="_CustomerOrders", ThisKey="UserID", OtherKey="CustomerID")]
		public EntitySet<CustomerOrder> CustomerOrders
		{
			get
			{
				return this._CustomerOrders;
			}
			set
			{
				this._CustomerOrders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_CustomerSkinCondition", Storage="_CustomerSkinConditions", ThisKey="UserID", OtherKey="CustomerID")]
		public EntitySet<CustomerSkinCondition> CustomerSkinConditions
		{
			get
			{
				return this._CustomerSkinConditions;
			}
			set
			{
				this._CustomerSkinConditions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_REVIEW", Storage="_REVIEWs", ThisKey="UserID", OtherKey="CustomerID")]
		public EntitySet<REVIEW> REVIEWs
		{
			get
			{
				return this._REVIEWs;
			}
			set
			{
				this._REVIEWs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserAddress_AppUser", Storage="_UserAddress", ThisKey="BillingAddressID", OtherKey="AddressID", IsForeignKey=true)]
		public UserAddress UserAddress
		{
			get
			{
				return this._UserAddress.Entity;
			}
			set
			{
				UserAddress previousValue = this._UserAddress.Entity;
				if (((previousValue != value) 
							|| (this._UserAddress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserAddress.Entity = null;
						previousValue.AppUsers.Remove(this);
					}
					this._UserAddress.Entity = value;
					if ((value != null))
					{
						value.AppUsers.Add(this);
						this._BillingAddressID = value.AddressID;
					}
					else
					{
						this._BillingAddressID = default(Nullable<int>);
					}
					this.SendPropertyChanged("UserAddress");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserAddress_AppUser1", Storage="_UserAddress1", ThisKey="ShippingAddressID", OtherKey="AddressID", IsForeignKey=true)]
		public UserAddress UserAddress1
		{
			get
			{
				return this._UserAddress1.Entity;
			}
			set
			{
				UserAddress previousValue = this._UserAddress1.Entity;
				if (((previousValue != value) 
							|| (this._UserAddress1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserAddress1.Entity = null;
						previousValue.AppUsers1.Remove(this);
					}
					this._UserAddress1.Entity = value;
					if ((value != null))
					{
						value.AppUsers1.Add(this);
						this._ShippingAddressID = value.AddressID;
					}
					else
					{
						this._ShippingAddressID = default(Nullable<int>);
					}
					this.SendPropertyChanged("UserAddress1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CustomerOrders(CustomerOrder entity)
		{
			this.SendPropertyChanging();
			entity.AppUser = this;
		}
		
		private void detach_CustomerOrders(CustomerOrder entity)
		{
			this.SendPropertyChanging();
			entity.AppUser = null;
		}
		
		private void attach_CustomerSkinConditions(CustomerSkinCondition entity)
		{
			this.SendPropertyChanging();
			entity.AppUser = this;
		}
		
		private void detach_CustomerSkinConditions(CustomerSkinCondition entity)
		{
			this.SendPropertyChanging();
			entity.AppUser = null;
		}
		
		private void attach_REVIEWs(REVIEW entity)
		{
			this.SendPropertyChanging();
			entity.AppUser = this;
		}
		
		private void detach_REVIEWs(REVIEW entity)
		{
			this.SendPropertyChanging();
			entity.AppUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BeautyProduct")]
	public partial class BeautyProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductID;
		
		private string _ProductName;
		
		private string _ProductDescription;
		
		private string _ProductType;
		
		private decimal _Price;
		
		private System.DateTime _DateAdded;
		
		private int _StockQuantity;
		
		private string _ImagePath;
		
		private EntitySet<BundleItem> _BundleItems;
		
		private EntitySet<OrderItem> _OrderItems;
		
		private EntitySet<REVIEW> _REVIEWs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnProductDescriptionChanging(string value);
    partial void OnProductDescriptionChanged();
    partial void OnProductTypeChanging(string value);
    partial void OnProductTypeChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnDateAddedChanging(System.DateTime value);
    partial void OnDateAddedChanged();
    partial void OnStockQuantityChanging(int value);
    partial void OnStockQuantityChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    #endregion
		
		public BeautyProduct()
		{
			this._BundleItems = new EntitySet<BundleItem>(new Action<BundleItem>(this.attach_BundleItems), new Action<BundleItem>(this.detach_BundleItems));
			this._OrderItems = new EntitySet<OrderItem>(new Action<OrderItem>(this.attach_OrderItems), new Action<OrderItem>(this.detach_OrderItems));
			this._REVIEWs = new EntitySet<REVIEW>(new Action<REVIEW>(this.attach_REVIEWs), new Action<REVIEW>(this.detach_REVIEWs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProductDescription
		{
			get
			{
				return this._ProductDescription;
			}
			set
			{
				if ((this._ProductDescription != value))
				{
					this.OnProductDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ProductDescription = value;
					this.SendPropertyChanged("ProductDescription");
					this.OnProductDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this.OnProductTypeChanging(value);
					this.SendPropertyChanging();
					this._ProductType = value;
					this.SendPropertyChanged("ProductType");
					this.OnProductTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(10,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime NOT NULL")]
		public System.DateTime DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockQuantity", DbType="Int NOT NULL")]
		public int StockQuantity
		{
			get
			{
				return this._StockQuantity;
			}
			set
			{
				if ((this._StockQuantity != value))
				{
					this.OnStockQuantityChanging(value);
					this.SendPropertyChanging();
					this._StockQuantity = value;
					this.SendPropertyChanged("StockQuantity");
					this.OnStockQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BeautyProduct_BundleItem", Storage="_BundleItems", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<BundleItem> BundleItems
		{
			get
			{
				return this._BundleItems;
			}
			set
			{
				this._BundleItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BeautyProduct_OrderItem", Storage="_OrderItems", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<OrderItem> OrderItems
		{
			get
			{
				return this._OrderItems;
			}
			set
			{
				this._OrderItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BeautyProduct_REVIEW", Storage="_REVIEWs", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<REVIEW> REVIEWs
		{
			get
			{
				return this._REVIEWs;
			}
			set
			{
				this._REVIEWs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BundleItems(BundleItem entity)
		{
			this.SendPropertyChanging();
			entity.BeautyProduct = this;
		}
		
		private void detach_BundleItems(BundleItem entity)
		{
			this.SendPropertyChanging();
			entity.BeautyProduct = null;
		}
		
		private void attach_OrderItems(OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.BeautyProduct = this;
		}
		
		private void detach_OrderItems(OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.BeautyProduct = null;
		}
		
		private void attach_REVIEWs(REVIEW entity)
		{
			this.SendPropertyChanging();
			entity.BeautyProduct = this;
		}
		
		private void detach_REVIEWs(REVIEW entity)
		{
			this.SendPropertyChanging();
			entity.BeautyProduct = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BundleItem")]
	public partial class BundleItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BundleID;
		
		private int _ProductID;
		
		private int _Quantity;
		
		private EntityRef<BeautyProduct> _BeautyProduct;
		
		private EntityRef<BundlePackage> _BundlePackage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBundleIDChanging(int value);
    partial void OnBundleIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    #endregion
		
		public BundleItem()
		{
			this._BeautyProduct = default(EntityRef<BeautyProduct>);
			this._BundlePackage = default(EntityRef<BundlePackage>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BundleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BundleID
		{
			get
			{
				return this._BundleID;
			}
			set
			{
				if ((this._BundleID != value))
				{
					if (this._BundlePackage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBundleIDChanging(value);
					this.SendPropertyChanging();
					this._BundleID = value;
					this.SendPropertyChanged("BundleID");
					this.OnBundleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._BeautyProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BeautyProduct_BundleItem", Storage="_BeautyProduct", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public BeautyProduct BeautyProduct
		{
			get
			{
				return this._BeautyProduct.Entity;
			}
			set
			{
				BeautyProduct previousValue = this._BeautyProduct.Entity;
				if (((previousValue != value) 
							|| (this._BeautyProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BeautyProduct.Entity = null;
						previousValue.BundleItems.Remove(this);
					}
					this._BeautyProduct.Entity = value;
					if ((value != null))
					{
						value.BundleItems.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("BeautyProduct");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BundlePackage_BundleItem", Storage="_BundlePackage", ThisKey="BundleID", OtherKey="BundleID", IsForeignKey=true)]
		public BundlePackage BundlePackage
		{
			get
			{
				return this._BundlePackage.Entity;
			}
			set
			{
				BundlePackage previousValue = this._BundlePackage.Entity;
				if (((previousValue != value) 
							|| (this._BundlePackage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BundlePackage.Entity = null;
						previousValue.BundleItems.Remove(this);
					}
					this._BundlePackage.Entity = value;
					if ((value != null))
					{
						value.BundleItems.Add(this);
						this._BundleID = value.BundleID;
					}
					else
					{
						this._BundleID = default(int);
					}
					this.SendPropertyChanged("BundlePackage");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BundlePackage")]
	public partial class BundlePackage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BundleID;
		
		private string _BundleName;
		
		private string _BundleDescription;
		
		private decimal _BundlePrice;
		
		private System.DateTime _DateAdded;
		
		private EntitySet<BundleItem> _BundleItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBundleIDChanging(int value);
    partial void OnBundleIDChanged();
    partial void OnBundleNameChanging(string value);
    partial void OnBundleNameChanged();
    partial void OnBundleDescriptionChanging(string value);
    partial void OnBundleDescriptionChanged();
    partial void OnBundlePriceChanging(decimal value);
    partial void OnBundlePriceChanged();
    partial void OnDateAddedChanging(System.DateTime value);
    partial void OnDateAddedChanged();
    #endregion
		
		public BundlePackage()
		{
			this._BundleItems = new EntitySet<BundleItem>(new Action<BundleItem>(this.attach_BundleItems), new Action<BundleItem>(this.detach_BundleItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BundleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BundleID
		{
			get
			{
				return this._BundleID;
			}
			set
			{
				if ((this._BundleID != value))
				{
					this.OnBundleIDChanging(value);
					this.SendPropertyChanging();
					this._BundleID = value;
					this.SendPropertyChanged("BundleID");
					this.OnBundleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BundleName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string BundleName
		{
			get
			{
				return this._BundleName;
			}
			set
			{
				if ((this._BundleName != value))
				{
					this.OnBundleNameChanging(value);
					this.SendPropertyChanging();
					this._BundleName = value;
					this.SendPropertyChanged("BundleName");
					this.OnBundleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BundleDescription", DbType="VarChar(MAX)")]
		public string BundleDescription
		{
			get
			{
				return this._BundleDescription;
			}
			set
			{
				if ((this._BundleDescription != value))
				{
					this.OnBundleDescriptionChanging(value);
					this.SendPropertyChanging();
					this._BundleDescription = value;
					this.SendPropertyChanged("BundleDescription");
					this.OnBundleDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BundlePrice", DbType="Decimal(10,2) NOT NULL")]
		public decimal BundlePrice
		{
			get
			{
				return this._BundlePrice;
			}
			set
			{
				if ((this._BundlePrice != value))
				{
					this.OnBundlePriceChanging(value);
					this.SendPropertyChanging();
					this._BundlePrice = value;
					this.SendPropertyChanged("BundlePrice");
					this.OnBundlePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime NOT NULL")]
		public System.DateTime DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BundlePackage_BundleItem", Storage="_BundleItems", ThisKey="BundleID", OtherKey="BundleID")]
		public EntitySet<BundleItem> BundleItems
		{
			get
			{
				return this._BundleItems;
			}
			set
			{
				this._BundleItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BundleItems(BundleItem entity)
		{
			this.SendPropertyChanging();
			entity.BundlePackage = this;
		}
		
		private void detach_BundleItems(BundleItem entity)
		{
			this.SendPropertyChanging();
			entity.BundlePackage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerOrder")]
	public partial class CustomerOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OrderID;
		
		private int _CustomerID;
		
		private int _ShippingAddressID;
		
		private int _BillingAddressID;
		
		private System.DateTime _DateOrdered;
		
		private string _OrderStatus;
		
		private decimal _TotalAmount;
		
		private EntitySet<OrderItem> _OrderItems;
		
		private EntityRef<AppUser> _AppUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderIDChanging(int value);
    partial void OnOrderIDChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnShippingAddressIDChanging(int value);
    partial void OnShippingAddressIDChanged();
    partial void OnBillingAddressIDChanging(int value);
    partial void OnBillingAddressIDChanged();
    partial void OnDateOrderedChanging(System.DateTime value);
    partial void OnDateOrderedChanged();
    partial void OnOrderStatusChanging(string value);
    partial void OnOrderStatusChanged();
    partial void OnTotalAmountChanging(decimal value);
    partial void OnTotalAmountChanged();
    #endregion
		
		public CustomerOrder()
		{
			this._OrderItems = new EntitySet<OrderItem>(new Action<OrderItem>(this.attach_OrderItems), new Action<OrderItem>(this.detach_OrderItems));
			this._AppUser = default(EntityRef<AppUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this.OnOrderIDChanging(value);
					this.SendPropertyChanging();
					this._OrderID = value;
					this.SendPropertyChanged("OrderID");
					this.OnOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					if (this._AppUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddressID", DbType="Int NOT NULL")]
		public int ShippingAddressID
		{
			get
			{
				return this._ShippingAddressID;
			}
			set
			{
				if ((this._ShippingAddressID != value))
				{
					this.OnShippingAddressIDChanging(value);
					this.SendPropertyChanging();
					this._ShippingAddressID = value;
					this.SendPropertyChanged("ShippingAddressID");
					this.OnShippingAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddressID", DbType="Int NOT NULL")]
		public int BillingAddressID
		{
			get
			{
				return this._BillingAddressID;
			}
			set
			{
				if ((this._BillingAddressID != value))
				{
					this.OnBillingAddressIDChanging(value);
					this.SendPropertyChanging();
					this._BillingAddressID = value;
					this.SendPropertyChanged("BillingAddressID");
					this.OnBillingAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOrdered", DbType="DateTime NOT NULL")]
		public System.DateTime DateOrdered
		{
			get
			{
				return this._DateOrdered;
			}
			set
			{
				if ((this._DateOrdered != value))
				{
					this.OnDateOrderedChanging(value);
					this.SendPropertyChanging();
					this._DateOrdered = value;
					this.SendPropertyChanged("DateOrdered");
					this.OnDateOrderedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderStatus", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string OrderStatus
		{
			get
			{
				return this._OrderStatus;
			}
			set
			{
				if ((this._OrderStatus != value))
				{
					this.OnOrderStatusChanging(value);
					this.SendPropertyChanging();
					this._OrderStatus = value;
					this.SendPropertyChanged("OrderStatus");
					this.OnOrderStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(10,2) NOT NULL")]
		public decimal TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this.OnTotalAmountChanging(value);
					this.SendPropertyChanging();
					this._TotalAmount = value;
					this.SendPropertyChanged("TotalAmount");
					this.OnTotalAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerOrder_OrderItem", Storage="_OrderItems", ThisKey="OrderID", OtherKey="OrderID")]
		public EntitySet<OrderItem> OrderItems
		{
			get
			{
				return this._OrderItems;
			}
			set
			{
				this._OrderItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_CustomerOrder", Storage="_AppUser", ThisKey="CustomerID", OtherKey="UserID", IsForeignKey=true)]
		public AppUser AppUser
		{
			get
			{
				return this._AppUser.Entity;
			}
			set
			{
				AppUser previousValue = this._AppUser.Entity;
				if (((previousValue != value) 
							|| (this._AppUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AppUser.Entity = null;
						previousValue.CustomerOrders.Remove(this);
					}
					this._AppUser.Entity = value;
					if ((value != null))
					{
						value.CustomerOrders.Add(this);
						this._CustomerID = value.UserID;
					}
					else
					{
						this._CustomerID = default(int);
					}
					this.SendPropertyChanged("AppUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OrderItems(OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.CustomerOrder = this;
		}
		
		private void detach_OrderItems(OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.CustomerOrder = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerSkinCondition")]
	public partial class CustomerSkinCondition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerID;
		
		private int _ConditionID;
		
		private EntityRef<AppUser> _AppUser;
		
		private EntityRef<SkinCondition> _SkinCondition;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnConditionIDChanging(int value);
    partial void OnConditionIDChanged();
    #endregion
		
		public CustomerSkinCondition()
		{
			this._AppUser = default(EntityRef<AppUser>);
			this._SkinCondition = default(EntityRef<SkinCondition>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					if (this._AppUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ConditionID
		{
			get
			{
				return this._ConditionID;
			}
			set
			{
				if ((this._ConditionID != value))
				{
					if (this._SkinCondition.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnConditionIDChanging(value);
					this.SendPropertyChanging();
					this._ConditionID = value;
					this.SendPropertyChanged("ConditionID");
					this.OnConditionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_CustomerSkinCondition", Storage="_AppUser", ThisKey="CustomerID", OtherKey="UserID", IsForeignKey=true)]
		public AppUser AppUser
		{
			get
			{
				return this._AppUser.Entity;
			}
			set
			{
				AppUser previousValue = this._AppUser.Entity;
				if (((previousValue != value) 
							|| (this._AppUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AppUser.Entity = null;
						previousValue.CustomerSkinConditions.Remove(this);
					}
					this._AppUser.Entity = value;
					if ((value != null))
					{
						value.CustomerSkinConditions.Add(this);
						this._CustomerID = value.UserID;
					}
					else
					{
						this._CustomerID = default(int);
					}
					this.SendPropertyChanged("AppUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SkinCondition_CustomerSkinCondition", Storage="_SkinCondition", ThisKey="ConditionID", OtherKey="ConditionID", IsForeignKey=true)]
		public SkinCondition SkinCondition
		{
			get
			{
				return this._SkinCondition.Entity;
			}
			set
			{
				SkinCondition previousValue = this._SkinCondition.Entity;
				if (((previousValue != value) 
							|| (this._SkinCondition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SkinCondition.Entity = null;
						previousValue.CustomerSkinConditions.Remove(this);
					}
					this._SkinCondition.Entity = value;
					if ((value != null))
					{
						value.CustomerSkinConditions.Add(this);
						this._ConditionID = value.ConditionID;
					}
					else
					{
						this._ConditionID = default(int);
					}
					this.SendPropertyChanged("SkinCondition");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderItem")]
	public partial class OrderItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ItemID;
		
		private int _OrderID;
		
		private int _ProductID;
		
		private int _ProductQuantity;
		
		private decimal _UnitPrice;
		
		private EntityRef<CustomerOrder> _CustomerOrder;
		
		private EntityRef<BeautyProduct> _BeautyProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemIDChanging(int value);
    partial void OnItemIDChanged();
    partial void OnOrderIDChanging(int value);
    partial void OnOrderIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnProductQuantityChanging(int value);
    partial void OnProductQuantityChanged();
    partial void OnUnitPriceChanging(decimal value);
    partial void OnUnitPriceChanged();
    #endregion
		
		public OrderItem()
		{
			this._CustomerOrder = default(EntityRef<CustomerOrder>);
			this._BeautyProduct = default(EntityRef<BeautyProduct>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this.OnItemIDChanging(value);
					this.SendPropertyChanging();
					this._ItemID = value;
					this.SendPropertyChanged("ItemID");
					this.OnItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="Int NOT NULL")]
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					if (this._CustomerOrder.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrderIDChanging(value);
					this.SendPropertyChanging();
					this._OrderID = value;
					this.SendPropertyChanged("OrderID");
					this.OnOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._BeautyProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductQuantity", DbType="Int NOT NULL")]
		public int ProductQuantity
		{
			get
			{
				return this._ProductQuantity;
			}
			set
			{
				if ((this._ProductQuantity != value))
				{
					this.OnProductQuantityChanging(value);
					this.SendPropertyChanging();
					this._ProductQuantity = value;
					this.SendPropertyChanged("ProductQuantity");
					this.OnProductQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Decimal(10,2) NOT NULL")]
		public decimal UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this.OnUnitPriceChanging(value);
					this.SendPropertyChanging();
					this._UnitPrice = value;
					this.SendPropertyChanged("UnitPrice");
					this.OnUnitPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerOrder_OrderItem", Storage="_CustomerOrder", ThisKey="OrderID", OtherKey="OrderID", IsForeignKey=true)]
		public CustomerOrder CustomerOrder
		{
			get
			{
				return this._CustomerOrder.Entity;
			}
			set
			{
				CustomerOrder previousValue = this._CustomerOrder.Entity;
				if (((previousValue != value) 
							|| (this._CustomerOrder.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CustomerOrder.Entity = null;
						previousValue.OrderItems.Remove(this);
					}
					this._CustomerOrder.Entity = value;
					if ((value != null))
					{
						value.OrderItems.Add(this);
						this._OrderID = value.OrderID;
					}
					else
					{
						this._OrderID = default(int);
					}
					this.SendPropertyChanged("CustomerOrder");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BeautyProduct_OrderItem", Storage="_BeautyProduct", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public BeautyProduct BeautyProduct
		{
			get
			{
				return this._BeautyProduct.Entity;
			}
			set
			{
				BeautyProduct previousValue = this._BeautyProduct.Entity;
				if (((previousValue != value) 
							|| (this._BeautyProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BeautyProduct.Entity = null;
						previousValue.OrderItems.Remove(this);
					}
					this._BeautyProduct.Entity = value;
					if ((value != null))
					{
						value.OrderItems.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("BeautyProduct");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REVIEW")]
	public partial class REVIEW : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReviewID;
		
		private int _ProductID;
		
		private int _CustomerID;
		
		private string _ReviewText;
		
		private int _Rating;
		
		private EntityRef<AppUser> _AppUser;
		
		private EntityRef<BeautyProduct> _BeautyProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReviewIDChanging(int value);
    partial void OnReviewIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnReviewTextChanging(string value);
    partial void OnReviewTextChanged();
    partial void OnRatingChanging(int value);
    partial void OnRatingChanged();
    #endregion
		
		public REVIEW()
		{
			this._AppUser = default(EntityRef<AppUser>);
			this._BeautyProduct = default(EntityRef<BeautyProduct>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReviewID
		{
			get
			{
				return this._ReviewID;
			}
			set
			{
				if ((this._ReviewID != value))
				{
					this.OnReviewIDChanging(value);
					this.SendPropertyChanging();
					this._ReviewID = value;
					this.SendPropertyChanged("ReviewID");
					this.OnReviewIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._BeautyProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					if (this._AppUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewText", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ReviewText
		{
			get
			{
				return this._ReviewText;
			}
			set
			{
				if ((this._ReviewText != value))
				{
					this.OnReviewTextChanging(value);
					this.SendPropertyChanging();
					this._ReviewText = value;
					this.SendPropertyChanged("ReviewText");
					this.OnReviewTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int NOT NULL")]
		public int Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AppUser_REVIEW", Storage="_AppUser", ThisKey="CustomerID", OtherKey="UserID", IsForeignKey=true)]
		public AppUser AppUser
		{
			get
			{
				return this._AppUser.Entity;
			}
			set
			{
				AppUser previousValue = this._AppUser.Entity;
				if (((previousValue != value) 
							|| (this._AppUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AppUser.Entity = null;
						previousValue.REVIEWs.Remove(this);
					}
					this._AppUser.Entity = value;
					if ((value != null))
					{
						value.REVIEWs.Add(this);
						this._CustomerID = value.UserID;
					}
					else
					{
						this._CustomerID = default(int);
					}
					this.SendPropertyChanged("AppUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BeautyProduct_REVIEW", Storage="_BeautyProduct", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public BeautyProduct BeautyProduct
		{
			get
			{
				return this._BeautyProduct.Entity;
			}
			set
			{
				BeautyProduct previousValue = this._BeautyProduct.Entity;
				if (((previousValue != value) 
							|| (this._BeautyProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BeautyProduct.Entity = null;
						previousValue.REVIEWs.Remove(this);
					}
					this._BeautyProduct.Entity = value;
					if ((value != null))
					{
						value.REVIEWs.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("BeautyProduct");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SkinCondition")]
	public partial class SkinCondition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ConditionID;
		
		private string _ConditionType;
		
		private EntitySet<CustomerSkinCondition> _CustomerSkinConditions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConditionIDChanging(int value);
    partial void OnConditionIDChanged();
    partial void OnConditionTypeChanging(string value);
    partial void OnConditionTypeChanged();
    #endregion
		
		public SkinCondition()
		{
			this._CustomerSkinConditions = new EntitySet<CustomerSkinCondition>(new Action<CustomerSkinCondition>(this.attach_CustomerSkinConditions), new Action<CustomerSkinCondition>(this.detach_CustomerSkinConditions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ConditionID
		{
			get
			{
				return this._ConditionID;
			}
			set
			{
				if ((this._ConditionID != value))
				{
					this.OnConditionIDChanging(value);
					this.SendPropertyChanging();
					this._ConditionID = value;
					this.SendPropertyChanged("ConditionID");
					this.OnConditionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionType", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ConditionType
		{
			get
			{
				return this._ConditionType;
			}
			set
			{
				if ((this._ConditionType != value))
				{
					this.OnConditionTypeChanging(value);
					this.SendPropertyChanging();
					this._ConditionType = value;
					this.SendPropertyChanged("ConditionType");
					this.OnConditionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SkinCondition_CustomerSkinCondition", Storage="_CustomerSkinConditions", ThisKey="ConditionID", OtherKey="ConditionID")]
		public EntitySet<CustomerSkinCondition> CustomerSkinConditions
		{
			get
			{
				return this._CustomerSkinConditions;
			}
			set
			{
				this._CustomerSkinConditions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CustomerSkinConditions(CustomerSkinCondition entity)
		{
			this.SendPropertyChanging();
			entity.SkinCondition = this;
		}
		
		private void detach_CustomerSkinConditions(CustomerSkinCondition entity)
		{
			this.SendPropertyChanging();
			entity.SkinCondition = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserAddress")]
	public partial class UserAddress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AddressID;
		
		private string _AddressType;
		
		private string _StreetLine1;
		
		private string _StreetLine2;
		
		private string _City;
		
		private string _StateOrProvince;
		
		private string _PostalCode;
		
		private string _Country;
		
		private EntitySet<AppUser> _AppUsers;
		
		private EntitySet<AppUser> _AppUsers1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAddressIDChanging(int value);
    partial void OnAddressIDChanged();
    partial void OnAddressTypeChanging(string value);
    partial void OnAddressTypeChanged();
    partial void OnStreetLine1Changing(string value);
    partial void OnStreetLine1Changed();
    partial void OnStreetLine2Changing(string value);
    partial void OnStreetLine2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateOrProvinceChanging(string value);
    partial void OnStateOrProvinceChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    #endregion
		
		public UserAddress()
		{
			this._AppUsers = new EntitySet<AppUser>(new Action<AppUser>(this.attach_AppUsers), new Action<AppUser>(this.detach_AppUsers));
			this._AppUsers1 = new EntitySet<AppUser>(new Action<AppUser>(this.attach_AppUsers1), new Action<AppUser>(this.detach_AppUsers1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AddressID
		{
			get
			{
				return this._AddressID;
			}
			set
			{
				if ((this._AddressID != value))
				{
					this.OnAddressIDChanging(value);
					this.SendPropertyChanging();
					this._AddressID = value;
					this.SendPropertyChanged("AddressID");
					this.OnAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressType", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string AddressType
		{
			get
			{
				return this._AddressType;
			}
			set
			{
				if ((this._AddressType != value))
				{
					this.OnAddressTypeChanging(value);
					this.SendPropertyChanging();
					this._AddressType = value;
					this.SendPropertyChanged("AddressType");
					this.OnAddressTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetLine1", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StreetLine1
		{
			get
			{
				return this._StreetLine1;
			}
			set
			{
				if ((this._StreetLine1 != value))
				{
					this.OnStreetLine1Changing(value);
					this.SendPropertyChanging();
					this._StreetLine1 = value;
					this.SendPropertyChanged("StreetLine1");
					this.OnStreetLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetLine2", DbType="VarChar(MAX)")]
		public string StreetLine2
		{
			get
			{
				return this._StreetLine2;
			}
			set
			{
				if ((this._StreetLine2 != value))
				{
					this.OnStreetLine2Changing(value);
					this.SendPropertyChanging();
					this._StreetLine2 = value;
					this.SendPropertyChanged("StreetLine2");
					this.OnStreetLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateOrProvince", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StateOrProvince
		{
			get
			{
				return this._StateOrProvince;
			}
			set
			{
				if ((this._StateOrProvince != value))
				{
					this.OnStateOrProvinceChanging(value);
					this.SendPropertyChanging();
					this._StateOrProvince = value;
					this.SendPropertyChanged("StateOrProvince");
					this.OnStateOrProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserAddress_AppUser", Storage="_AppUsers", ThisKey="AddressID", OtherKey="BillingAddressID")]
		public EntitySet<AppUser> AppUsers
		{
			get
			{
				return this._AppUsers;
			}
			set
			{
				this._AppUsers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserAddress_AppUser1", Storage="_AppUsers1", ThisKey="AddressID", OtherKey="ShippingAddressID")]
		public EntitySet<AppUser> AppUsers1
		{
			get
			{
				return this._AppUsers1;
			}
			set
			{
				this._AppUsers1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AppUsers(AppUser entity)
		{
			this.SendPropertyChanging();
			entity.UserAddress = this;
		}
		
		private void detach_AppUsers(AppUser entity)
		{
			this.SendPropertyChanging();
			entity.UserAddress = null;
		}
		
		private void attach_AppUsers1(AppUser entity)
		{
			this.SendPropertyChanging();
			entity.UserAddress1 = this;
		}
		
		private void detach_AppUsers1(AppUser entity)
		{
			this.SendPropertyChanging();
			entity.UserAddress1 = null;
		}
	}
}
#pragma warning restore 1591
