//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadientFrontEnd.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppUser", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class AppUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.Administrator AdministratorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BillingAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.CustomerOrder[] CustomerOrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.CustomerSkinCondition[] CustomerSkinConditionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashedPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.REVIEW[] REVIEWsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResetTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ResetTokenExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShippingAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.UserAddress UserAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.UserAddress UserAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VerificationExpiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerificationTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.Administrator Administrator {
            get {
                return this.AdministratorField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministratorField, value) != true)) {
                    this.AdministratorField = value;
                    this.RaisePropertyChanged("Administrator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BillingAddressID {
            get {
                return this.BillingAddressIDField;
            }
            set {
                if ((this.BillingAddressIDField.Equals(value) != true)) {
                    this.BillingAddressIDField = value;
                    this.RaisePropertyChanged("BillingAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.CustomerOrder[] CustomerOrders {
            get {
                return this.CustomerOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrdersField, value) != true)) {
                    this.CustomerOrdersField = value;
                    this.RaisePropertyChanged("CustomerOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.CustomerSkinCondition[] CustomerSkinConditions {
            get {
                return this.CustomerSkinConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSkinConditionsField, value) != true)) {
                    this.CustomerSkinConditionsField = value;
                    this.RaisePropertyChanged("CustomerSkinConditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashedPassword {
            get {
                return this.HashedPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashedPasswordField, value) != true)) {
                    this.HashedPasswordField = value;
                    this.RaisePropertyChanged("HashedPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsVerified {
            get {
                return this.IsVerifiedField;
            }
            set {
                if ((this.IsVerifiedField.Equals(value) != true)) {
                    this.IsVerifiedField = value;
                    this.RaisePropertyChanged("IsVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.REVIEW[] REVIEWs {
            get {
                return this.REVIEWsField;
            }
            set {
                if ((object.ReferenceEquals(this.REVIEWsField, value) != true)) {
                    this.REVIEWsField = value;
                    this.RaisePropertyChanged("REVIEWs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Race {
            get {
                return this.RaceField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceField, value) != true)) {
                    this.RaceField = value;
                    this.RaisePropertyChanged("Race");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResetToken {
            get {
                return this.ResetTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ResetTokenField, value) != true)) {
                    this.ResetTokenField = value;
                    this.RaisePropertyChanged("ResetToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ResetTokenExpiry {
            get {
                return this.ResetTokenExpiryField;
            }
            set {
                if ((this.ResetTokenExpiryField.Equals(value) != true)) {
                    this.ResetTokenExpiryField = value;
                    this.RaisePropertyChanged("ResetTokenExpiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShippingAddressID {
            get {
                return this.ShippingAddressIDField;
            }
            set {
                if ((this.ShippingAddressIDField.Equals(value) != true)) {
                    this.ShippingAddressIDField = value;
                    this.RaisePropertyChanged("ShippingAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.UserAddress UserAddress {
            get {
                return this.UserAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAddressField, value) != true)) {
                    this.UserAddressField = value;
                    this.RaisePropertyChanged("UserAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.UserAddress UserAddress1 {
            get {
                return this.UserAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserAddress1Field, value) != true)) {
                    this.UserAddress1Field = value;
                    this.RaisePropertyChanged("UserAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VerificationExpiry {
            get {
                return this.VerificationExpiryField;
            }
            set {
                if ((this.VerificationExpiryField.Equals(value) != true)) {
                    this.VerificationExpiryField = value;
                    this.RaisePropertyChanged("VerificationExpiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerificationToken {
            get {
                return this.VerificationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.VerificationTokenField, value) != true)) {
                    this.VerificationTokenField = value;
                    this.RaisePropertyChanged("VerificationToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrator", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class Administrator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdminIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.AppUser AppUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAppointedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((this.AdminIDField.Equals(value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.AppUser AppUser {
            get {
                return this.AppUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUserField, value) != true)) {
                    this.AppUserField = value;
                    this.RaisePropertyChanged("AppUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAppointed {
            get {
                return this.DateAppointedField;
            }
            set {
                if ((this.DateAppointedField.Equals(value) != true)) {
                    this.DateAppointedField = value;
                    this.RaisePropertyChanged("DateAppointed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAddress", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class UserAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.AppUser[] AppUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.AppUser[] AppUsers1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateOrProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetLine2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressTypeField, value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.AppUser[] AppUsers {
            get {
                return this.AppUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUsersField, value) != true)) {
                    this.AppUsersField = value;
                    this.RaisePropertyChanged("AppUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.AppUser[] AppUsers1 {
            get {
                return this.AppUsers1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AppUsers1Field, value) != true)) {
                    this.AppUsers1Field = value;
                    this.RaisePropertyChanged("AppUsers1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateOrProvince {
            get {
                return this.StateOrProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateOrProvinceField, value) != true)) {
                    this.StateOrProvinceField = value;
                    this.RaisePropertyChanged("StateOrProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetLine1 {
            get {
                return this.StreetLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.StreetLine1Field, value) != true)) {
                    this.StreetLine1Field = value;
                    this.RaisePropertyChanged("StreetLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetLine2 {
            get {
                return this.StreetLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.StreetLine2Field, value) != true)) {
                    this.StreetLine2Field = value;
                    this.RaisePropertyChanged("StreetLine2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerOrder", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class CustomerOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.AppUser AppUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillingAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOrderedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.OrderItem[] OrderItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShippingAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.AppUser AppUser {
            get {
                return this.AppUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUserField, value) != true)) {
                    this.AppUserField = value;
                    this.RaisePropertyChanged("AppUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillingAddressID {
            get {
                return this.BillingAddressIDField;
            }
            set {
                if ((this.BillingAddressIDField.Equals(value) != true)) {
                    this.BillingAddressIDField = value;
                    this.RaisePropertyChanged("BillingAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOrdered {
            get {
                return this.DateOrderedField;
            }
            set {
                if ((this.DateOrderedField.Equals(value) != true)) {
                    this.DateOrderedField = value;
                    this.RaisePropertyChanged("DateOrdered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.OrderItem[] OrderItems {
            get {
                return this.OrderItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderItemsField, value) != true)) {
                    this.OrderItemsField = value;
                    this.RaisePropertyChanged("OrderItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShippingAddressID {
            get {
                return this.ShippingAddressIDField;
            }
            set {
                if ((this.ShippingAddressIDField.Equals(value) != true)) {
                    this.ShippingAddressIDField = value;
                    this.RaisePropertyChanged("ShippingAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerSkinCondition", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class CustomerSkinCondition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.AppUser AppUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConditionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.SkinCondition SkinConditionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.AppUser AppUser {
            get {
                return this.AppUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUserField, value) != true)) {
                    this.AppUserField = value;
                    this.RaisePropertyChanged("AppUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConditionID {
            get {
                return this.ConditionIDField;
            }
            set {
                if ((this.ConditionIDField.Equals(value) != true)) {
                    this.ConditionIDField = value;
                    this.RaisePropertyChanged("ConditionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.SkinCondition SkinCondition {
            get {
                return this.SkinConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.SkinConditionField, value) != true)) {
                    this.SkinConditionField = value;
                    this.RaisePropertyChanged("SkinCondition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REVIEW", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class REVIEW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.AppUser AppUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.BeautyProduct BeautyProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReviewIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.AppUser AppUser {
            get {
                return this.AppUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUserField, value) != true)) {
                    this.AppUserField = value;
                    this.RaisePropertyChanged("AppUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.BeautyProduct BeautyProduct {
            get {
                return this.BeautyProductField;
            }
            set {
                if ((object.ReferenceEquals(this.BeautyProductField, value) != true)) {
                    this.BeautyProductField = value;
                    this.RaisePropertyChanged("BeautyProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewID {
            get {
                return this.ReviewIDField;
            }
            set {
                if ((this.ReviewIDField.Equals(value) != true)) {
                    this.ReviewIDField = value;
                    this.RaisePropertyChanged("ReviewID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewText {
            get {
                return this.ReviewTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewTextField, value) != true)) {
                    this.ReviewTextField = value;
                    this.RaisePropertyChanged("ReviewText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class OrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.BeautyProduct BeautyProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.CustomerOrder CustomerOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.BeautyProduct BeautyProduct {
            get {
                return this.BeautyProductField;
            }
            set {
                if ((object.ReferenceEquals(this.BeautyProductField, value) != true)) {
                    this.BeautyProductField = value;
                    this.RaisePropertyChanged("BeautyProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.CustomerOrder CustomerOrder {
            get {
                return this.CustomerOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrderField, value) != true)) {
                    this.CustomerOrderField = value;
                    this.RaisePropertyChanged("CustomerOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductQuantity {
            get {
                return this.ProductQuantityField;
            }
            set {
                if ((this.ProductQuantityField.Equals(value) != true)) {
                    this.ProductQuantityField = value;
                    this.RaisePropertyChanged("ProductQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeautyProduct", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class BeautyProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.BundleItem[] BundleItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.OrderItem[] OrderItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.REVIEW[] REVIEWsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.BundleItem[] BundleItems {
            get {
                return this.BundleItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.BundleItemsField, value) != true)) {
                    this.BundleItemsField = value;
                    this.RaisePropertyChanged("BundleItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.OrderItem[] OrderItems {
            get {
                return this.OrderItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderItemsField, value) != true)) {
                    this.OrderItemsField = value;
                    this.RaisePropertyChanged("OrderItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription {
            get {
                return this.ProductDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescriptionField, value) != true)) {
                    this.ProductDescriptionField = value;
                    this.RaisePropertyChanged("ProductDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.REVIEW[] REVIEWs {
            get {
                return this.REVIEWsField;
            }
            set {
                if ((object.ReferenceEquals(this.REVIEWsField, value) != true)) {
                    this.REVIEWsField = value;
                    this.RaisePropertyChanged("REVIEWs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BundleItem", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class BundleItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.BeautyProduct BeautyProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BundleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.BundlePackage BundlePackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.BeautyProduct BeautyProduct {
            get {
                return this.BeautyProductField;
            }
            set {
                if ((object.ReferenceEquals(this.BeautyProductField, value) != true)) {
                    this.BeautyProductField = value;
                    this.RaisePropertyChanged("BeautyProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BundleID {
            get {
                return this.BundleIDField;
            }
            set {
                if ((this.BundleIDField.Equals(value) != true)) {
                    this.BundleIDField = value;
                    this.RaisePropertyChanged("BundleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.BundlePackage BundlePackage {
            get {
                return this.BundlePackageField;
            }
            set {
                if ((object.ReferenceEquals(this.BundlePackageField, value) != true)) {
                    this.BundlePackageField = value;
                    this.RaisePropertyChanged("BundlePackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BundlePackage", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class BundlePackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BundleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BundleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.BundleItem[] BundleItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BundleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BundlePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BundleDescription {
            get {
                return this.BundleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.BundleDescriptionField, value) != true)) {
                    this.BundleDescriptionField = value;
                    this.RaisePropertyChanged("BundleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BundleID {
            get {
                return this.BundleIDField;
            }
            set {
                if ((this.BundleIDField.Equals(value) != true)) {
                    this.BundleIDField = value;
                    this.RaisePropertyChanged("BundleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.BundleItem[] BundleItems {
            get {
                return this.BundleItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.BundleItemsField, value) != true)) {
                    this.BundleItemsField = value;
                    this.RaisePropertyChanged("BundleItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BundleName {
            get {
                return this.BundleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BundleNameField, value) != true)) {
                    this.BundleNameField = value;
                    this.RaisePropertyChanged("BundleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BundlePrice {
            get {
                return this.BundlePriceField;
            }
            set {
                if ((this.BundlePriceField.Equals(value) != true)) {
                    this.BundlePriceField = value;
                    this.RaisePropertyChanged("BundlePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkinCondition", Namespace="http://schemas.datacontract.org/2004/07/RadiantBeauty")]
    [System.SerializableAttribute()]
    public partial class SkinCondition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConditionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadientFrontEnd.ServiceReference1.CustomerSkinCondition[] CustomerSkinConditionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConditionID {
            get {
                return this.ConditionIDField;
            }
            set {
                if ((this.ConditionIDField.Equals(value) != true)) {
                    this.ConditionIDField = value;
                    this.RaisePropertyChanged("ConditionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConditionType {
            get {
                return this.ConditionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionTypeField, value) != true)) {
                    this.ConditionTypeField = value;
                    this.RaisePropertyChanged("ConditionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadientFrontEnd.ServiceReference1.CustomerSkinCondition[] CustomerSkinConditions {
            get {
                return this.CustomerSkinConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSkinConditionsField, value) != true)) {
                    this.CustomerSkinConditionsField = value;
                    this.RaisePropertyChanged("CustomerSkinConditions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        int Login(string Email, string PlainPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string Email, string PlainPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        void Register(RadientFrontEnd.ServiceReference1.AppUser u, string PlainPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(RadientFrontEnd.ServiceReference1.AppUser u, string PlainPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RadientFrontEnd.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RadientFrontEnd.ServiceReference1.IService1>, RadientFrontEnd.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string Email, string PlainPassword) {
            return base.Channel.Login(Email, PlainPassword);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string Email, string PlainPassword) {
            return base.Channel.LoginAsync(Email, PlainPassword);
        }
        
        public void Register(RadientFrontEnd.ServiceReference1.AppUser u, string PlainPassword) {
            base.Channel.Register(u, PlainPassword);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(RadientFrontEnd.ServiceReference1.AppUser u, string PlainPassword) {
            return base.Channel.RegisterAsync(u, PlainPassword);
        }
    }
}
