<?xml version="1.0" encoding="utf-8"?><Database Name="RadiantDB" Class="RadiantDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\RadiantDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RadiantDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Administrator" Member="Administrators">
    <Type Name="Administrator">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateAppointed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AppUser_Administrator" Member="AppUser" ThisKey="AdminID" OtherKey="UserID" Type="AppUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppUser" Member="AppUsers">
    <Type Name="AppUser">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserSurname" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="HashedPassword" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Race" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BillingAddressID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShippingAddressID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VerificationToken" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="VerificationExpiry" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResetToken" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="ResetTokenExpiry" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AppUser_Administrator" Member="Administrator" ThisKey="UserID" OtherKey="AdminID" Type="Administrator" Cardinality="One" />
      <Association Name="AppUser_CustomerOrder" Member="CustomerOrders" ThisKey="UserID" OtherKey="CustomerID" Type="CustomerOrder" />
      <Association Name="AppUser_CustomerSkinCondition" Member="CustomerSkinConditions" ThisKey="UserID" OtherKey="CustomerID" Type="CustomerSkinCondition" />
      <Association Name="AppUser_REVIEW" Member="REVIEWs" ThisKey="UserID" OtherKey="CustomerID" Type="REVIEW" />
      <Association Name="UserAddress_AppUser" Member="UserAddress" ThisKey="BillingAddressID" OtherKey="AddressID" Type="UserAddress" IsForeignKey="true" />
      <Association Name="UserAddress_AppUser1" Member="UserAddress1" ThisKey="ShippingAddressID" OtherKey="AddressID" Type="UserAddress" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BeautyProduct" Member="BeautyProducts">
    <Type Name="BeautyProduct">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProductDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StockQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="BeautyProduct_BundleItem" Member="BundleItems" ThisKey="ProductID" OtherKey="ProductID" Type="BundleItem" />
      <Association Name="BeautyProduct_OrderItem" Member="OrderItems" ThisKey="ProductID" OtherKey="ProductID" Type="OrderItem" />
      <Association Name="BeautyProduct_REVIEW" Member="REVIEWs" ThisKey="ProductID" OtherKey="ProductID" Type="REVIEW" />
    </Type>
  </Table>
  <Table Name="dbo.BundleItem" Member="BundleItems">
    <Type Name="BundleItem">
      <Column Name="BundleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BeautyProduct_BundleItem" Member="BeautyProduct" ThisKey="ProductID" OtherKey="ProductID" Type="BeautyProduct" IsForeignKey="true" />
      <Association Name="BundlePackage_BundleItem" Member="BundlePackage" ThisKey="BundleID" OtherKey="BundleID" Type="BundlePackage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BundlePackage" Member="BundlePackages">
    <Type Name="BundlePackage">
      <Column Name="BundleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BundleName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BundleDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BundlePrice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="BundlePackage_BundleItem" Member="BundleItems" ThisKey="BundleID" OtherKey="BundleID" Type="BundleItem" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerOrder" Member="CustomerOrders">
    <Type Name="CustomerOrder">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShippingAddressID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BillingAddressID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateOrdered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OrderStatus" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="CustomerOrder_OrderItem" Member="OrderItems" ThisKey="OrderID" OtherKey="OrderID" Type="OrderItem" />
      <Association Name="AppUser_CustomerOrder" Member="AppUser" ThisKey="CustomerID" OtherKey="UserID" Type="AppUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerSkinCondition" Member="CustomerSkinConditions">
    <Type Name="CustomerSkinCondition">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ConditionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AppUser_CustomerSkinCondition" Member="AppUser" ThisKey="CustomerID" OtherKey="UserID" Type="AppUser" IsForeignKey="true" />
      <Association Name="SkinCondition_CustomerSkinCondition" Member="SkinCondition" ThisKey="ConditionID" OtherKey="ConditionID" Type="SkinCondition" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItem" Member="OrderItems">
    <Type Name="OrderItem">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="CustomerOrder_OrderItem" Member="CustomerOrder" ThisKey="OrderID" OtherKey="OrderID" Type="CustomerOrder" IsForeignKey="true" />
      <Association Name="BeautyProduct_OrderItem" Member="BeautyProduct" ThisKey="ProductID" OtherKey="ProductID" Type="BeautyProduct" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.REVIEW" Member="REVIEWs">
    <Type Name="REVIEW">
      <Column Name="ReviewID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AppUser_REVIEW" Member="AppUser" ThisKey="CustomerID" OtherKey="UserID" Type="AppUser" IsForeignKey="true" />
      <Association Name="BeautyProduct_REVIEW" Member="BeautyProduct" ThisKey="ProductID" OtherKey="ProductID" Type="BeautyProduct" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SkinCondition" Member="SkinConditions">
    <Type Name="SkinCondition">
      <Column Name="ConditionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ConditionType" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="SkinCondition_CustomerSkinCondition" Member="CustomerSkinConditions" ThisKey="ConditionID" OtherKey="ConditionID" Type="CustomerSkinCondition" />
    </Type>
  </Table>
  <Table Name="dbo.UserAddress" Member="UserAddresses">
    <Type Name="UserAddress">
      <Column Name="AddressID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddressType" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StreetLine1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StreetLine2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StateOrProvince" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="UserAddress_AppUser" Member="AppUsers" ThisKey="AddressID" OtherKey="BillingAddressID" Type="AppUser" />
      <Association Name="UserAddress_AppUser1" Member="AppUsers1" ThisKey="AddressID" OtherKey="ShippingAddressID" Type="AppUser" />
    </Type>
  </Table>
</Database>